name: iot_clock
description: Clock application connected with a physical clock using MQTT protocol
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1


environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_mqtt: ^1.0.0+5
  flutter_screenutil: ^5.9.0
  page_animation_transition: ^1.0.0
  day_night_time_picker: ^1.3.0+1
  just_audio: ^0.9.36
  mqtt_client: ^10.0.0
  flutter_native_splash: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - Assets/Sounds/
    - Assets/Certificates/
    - Assets/Images/

  fonts:
    - family: Rubik
      fonts:
        - asset: Assets/Fonts/Rubik-Regular.ttf
        - asset: Assets/Fonts/Rubik-Medium.ttf
          weight: 500
        - asset: Assets/Fonts/Rubik-Bold.ttf
          weight: 700
